services:
  registry:
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    image: registry:2
    ports:
    - 5000:5000/tcp
    volumes:
    - registry-data:/var/lib/registry:rw
version: '3.0'
volumes:
  registry-data: {}

